meta:
  app_id: opal_tool_cmp_wi
  display_name: sample_opal_tool_cmp_wi
  version: 1.0.0-dev.37
  vendor: optimizely
  summary: Opal tool to create milestones within CMP
  support_url: https://support.optimizely.com
  contact_email: support@optimizely.com
  categories:
    - Personalization & Content
    - Opal
  availability:
    - all

runtime: node22

functions:
  opal_tool:
    entry_point: OpalToolFunction
    description: Opal tool function
